# Site wide configuration
production:
  url: http://dreamingechoes.github.io
development:
  url: http://localhost:4000

url: http://dreamingechoes.github.io
title: dreamingechoes
locale: en_EN

# Jekyll configuration
collections:
  tips:
    output: true
    permalink: /tips/:path/
  posts:
    output: true
    permalink: /:categories/:title/

permalink:   /:categories/:title/
markdown:    redcarpet
highlighter: pygments

sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Site owner
owner:
  name: Iv치n Gonz치lez
  avatar: bio-thumbnail-photo.jpg
  bio: Software developer @ <a href='http://simplelogica.net' target='_blank'>Simplelogica</a> <br> 100% geek and music freak
  disqus-shortname: dreamingechoes
  github: dreamingechoes
  linkedin: ivangonzalezsaiz
  twitter: dreamingechoes
  instagram: thedreamingechoes
  email: xixon.sound@gmail.com
  stackoverflow: 5218888/iv치n-gonz치lez
  lastfm: dreamingechoes
  disqus-shortname: dreamingechoes
  pinterest: dreamingechoes
  google:
    analytics: UA-65616587-2

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
